//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByteCarrot.Masslog.Web.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ByteCarrot.Masslog.Web.Infrastructure.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Administrators Group field is required..
        /// </summary>
        public static string AdminGroupRequiredMessage {
            get {
                return ResourceManager.GetString("AdminGroupRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application has been successfully added..
        /// </summary>
        public static string ApplicationAddedMessage {
            get {
                return ResourceManager.GetString("ApplicationAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application has been successfully deleted..
        /// </summary>
        public static string ApplicationDeletedMessage {
            get {
                return ResourceManager.GetString("ApplicationDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes in application&apos;s data have been successfully saved..
        /// </summary>
        public static string ApplicationEditedMessage {
            get {
                return ResourceManager.GetString("ApplicationEditedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified application name is already in use. Please choose another one..
        /// </summary>
        public static string ApplicationNameInUseMessage {
            get {
                return ResourceManager.GetString("ApplicationNameInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? All data in the form will be lost..
        /// </summary>
        public static string FormCancelConfirmMessage {
            get {
                return ResourceManager.GetString("FormCancelConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified password is invalid..
        /// </summary>
        public static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified username or password is invalid..
        /// </summary>
        public static string InvalidUsernamePasswordMessage {
            get {
                return ResourceManager.GetString("InvalidUsernamePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL.
        /// </summary>
        public static string MySqlMessage {
            get {
                return ResourceManager.GetString("MySqlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified user is not authorized to access any logs..
        /// </summary>
        public static string NotAuthorizedToAccessLogsMessage {
            get {
                return ResourceManager.GetString("NotAuthorizedToAccessLogsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field cannot contain white spaces or special characters..
        /// </summary>
        public static string NoWhiteSpacesOrSpecialCharsMessage {
            get {
                return ResourceManager.GetString("NoWhiteSpacesOrSpecialCharsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server.
        /// </summary>
        public static string SqlServerMessage {
            get {
                return ResourceManager.GetString("SqlServerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been successfully added..
        /// </summary>
        public static string UserAddedMessage {
            get {
                return ResourceManager.GetString("UserAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been successfully deleted..
        /// </summary>
        public static string UserDeletedMessage {
            get {
                return ResourceManager.GetString("UserDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes in user&apos;s data have been successfully saved..
        /// </summary>
        public static string UserEditedMessage {
            get {
                return ResourceManager.GetString("UserEditedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified username is already in use. Please choose another one..
        /// </summary>
        public static string UsernameInUseMessage {
            get {
                return ResourceManager.GetString("UsernameInUseMessage", resourceCulture);
            }
        }
    }
}
