// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ByteCarrot.Masslog.Web.Controllers.Activities
{
    public partial class ActivityController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActivityController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ActivityController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActivityController Actions { get { return MVC.Activity; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Activity";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Activity";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Details = "Details";
            public readonly string Request = "Request";
            public readonly string Response = "Response";
            public readonly string Exceptions = "Exceptions";
            public readonly string RouteData = "RouteData";
            public readonly string ServerVariables = "ServerVariables";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Details = "Details";
            public const string Request = "Request";
            public const string Response = "Response";
            public const string Exceptions = "Exceptions";
            public const string RouteData = "RouteData";
            public const string ServerVariables = "ServerVariables";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Details = "Details";
                public readonly string Exceptions = "Exceptions";
                public readonly string Index = "Index";
                public readonly string Request = "Request";
                public readonly string Response = "Response";
                public readonly string RouteData = "RouteData";
                public readonly string ServerVariables = "ServerVariables";
            }
            public readonly string Details = "~/Views/Activity/Details.cshtml";
            public readonly string Exceptions = "~/Views/Activity/Exceptions.cshtml";
            public readonly string Index = "~/Views/Activity/Index.cshtml";
            public readonly string Request = "~/Views/Activity/Request.cshtml";
            public readonly string Response = "~/Views/Activity/Response.cshtml";
            public readonly string RouteData = "~/Views/Activity/RouteData.cshtml";
            public readonly string ServerVariables = "~/Views/Activity/ServerVariables.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ActivityController : ByteCarrot.Masslog.Web.Controllers.Activities.ActivityController
    {
        public T4MVC_ActivityController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Details()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Request()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Request);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Response()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Response);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Exceptions()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Exceptions);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RouteData()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RouteData);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ServerVariables()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ServerVariables);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
