// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class InfrastructureController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ExtendedHtmlTableGridRenderer = "ExtendedHtmlTableGridRenderer";
                public readonly string ExtendedPager = "ExtendedPager";
                public readonly string FieldContainerExtensions = "FieldContainerExtensions";
                public readonly string GridColumnExtensions = "GridColumnExtensions";
                public readonly string MvcTools = "MvcTools";
                public readonly string TbFormExtensions = "TbFormExtensions";
                public readonly string ValidationExtensions = "ValidationExtensions";
            }
            public readonly string ExtendedHtmlTableGridRenderer = "~/Views/Infrastructure/ExtendedHtmlTableGridRenderer.cs";
            public readonly string ExtendedPager = "~/Views/Infrastructure/ExtendedPager.cs";
            public readonly string FieldContainerExtensions = "~/Views/Infrastructure/FieldContainerExtensions.cs";
            public readonly string GridColumnExtensions = "~/Views/Infrastructure/GridColumnExtensions.cs";
            public readonly string MvcTools = "~/Views/Infrastructure/MvcTools.cs";
            public readonly string TbFormExtensions = "~/Views/Infrastructure/TbFormExtensions.cs";
            public readonly string ValidationExtensions = "~/Views/Infrastructure/ValidationExtensions.cs";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
